// Do not edit this file directly!!!!!
namespace Bluehill.Deconstructors;

[EditorBrowsable(EditorBrowsableState.Never)]
public static class ReadOnlySpanDeconstructors {
    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1) {
        item1 = readOnlySpan[0];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
        item13 = readOnlySpan[12];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
        item13 = readOnlySpan[12];
        item14 = readOnlySpan[13];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
        item13 = readOnlySpan[12];
        item14 = readOnlySpan[13];
        item15 = readOnlySpan[14];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
        item13 = readOnlySpan[12];
        item14 = readOnlySpan[13];
        item15 = readOnlySpan[14];
        item16 = readOnlySpan[15];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
        item13 = readOnlySpan[12];
        item14 = readOnlySpan[13];
        item15 = readOnlySpan[14];
        item16 = readOnlySpan[15];
        item17 = readOnlySpan[16];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
        item13 = readOnlySpan[12];
        item14 = readOnlySpan[13];
        item15 = readOnlySpan[14];
        item16 = readOnlySpan[15];
        item17 = readOnlySpan[16];
        item18 = readOnlySpan[17];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
        item13 = readOnlySpan[12];
        item14 = readOnlySpan[13];
        item15 = readOnlySpan[14];
        item16 = readOnlySpan[15];
        item17 = readOnlySpan[16];
        item18 = readOnlySpan[17];
        item19 = readOnlySpan[18];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
        item13 = readOnlySpan[12];
        item14 = readOnlySpan[13];
        item15 = readOnlySpan[14];
        item16 = readOnlySpan[15];
        item17 = readOnlySpan[16];
        item18 = readOnlySpan[17];
        item19 = readOnlySpan[18];
        item20 = readOnlySpan[19];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
        item13 = readOnlySpan[12];
        item14 = readOnlySpan[13];
        item15 = readOnlySpan[14];
        item16 = readOnlySpan[15];
        item17 = readOnlySpan[16];
        item18 = readOnlySpan[17];
        item19 = readOnlySpan[18];
        item20 = readOnlySpan[19];
        item21 = readOnlySpan[20];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21, out T item22) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
        item13 = readOnlySpan[12];
        item14 = readOnlySpan[13];
        item15 = readOnlySpan[14];
        item16 = readOnlySpan[15];
        item17 = readOnlySpan[16];
        item18 = readOnlySpan[17];
        item19 = readOnlySpan[18];
        item20 = readOnlySpan[19];
        item21 = readOnlySpan[20];
        item22 = readOnlySpan[21];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21, out T item22, out T item23) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
        item13 = readOnlySpan[12];
        item14 = readOnlySpan[13];
        item15 = readOnlySpan[14];
        item16 = readOnlySpan[15];
        item17 = readOnlySpan[16];
        item18 = readOnlySpan[17];
        item19 = readOnlySpan[18];
        item20 = readOnlySpan[19];
        item21 = readOnlySpan[20];
        item22 = readOnlySpan[21];
        item23 = readOnlySpan[22];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21, out T item22, out T item23, out T item24) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
        item13 = readOnlySpan[12];
        item14 = readOnlySpan[13];
        item15 = readOnlySpan[14];
        item16 = readOnlySpan[15];
        item17 = readOnlySpan[16];
        item18 = readOnlySpan[17];
        item19 = readOnlySpan[18];
        item20 = readOnlySpan[19];
        item21 = readOnlySpan[20];
        item22 = readOnlySpan[21];
        item23 = readOnlySpan[22];
        item24 = readOnlySpan[23];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21, out T item22, out T item23, out T item24, out T item25) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
        item13 = readOnlySpan[12];
        item14 = readOnlySpan[13];
        item15 = readOnlySpan[14];
        item16 = readOnlySpan[15];
        item17 = readOnlySpan[16];
        item18 = readOnlySpan[17];
        item19 = readOnlySpan[18];
        item20 = readOnlySpan[19];
        item21 = readOnlySpan[20];
        item22 = readOnlySpan[21];
        item23 = readOnlySpan[22];
        item24 = readOnlySpan[23];
        item25 = readOnlySpan[24];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21, out T item22, out T item23, out T item24, out T item25, out T item26) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
        item13 = readOnlySpan[12];
        item14 = readOnlySpan[13];
        item15 = readOnlySpan[14];
        item16 = readOnlySpan[15];
        item17 = readOnlySpan[16];
        item18 = readOnlySpan[17];
        item19 = readOnlySpan[18];
        item20 = readOnlySpan[19];
        item21 = readOnlySpan[20];
        item22 = readOnlySpan[21];
        item23 = readOnlySpan[22];
        item24 = readOnlySpan[23];
        item25 = readOnlySpan[24];
        item26 = readOnlySpan[25];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21, out T item22, out T item23, out T item24, out T item25, out T item26, out T item27) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
        item13 = readOnlySpan[12];
        item14 = readOnlySpan[13];
        item15 = readOnlySpan[14];
        item16 = readOnlySpan[15];
        item17 = readOnlySpan[16];
        item18 = readOnlySpan[17];
        item19 = readOnlySpan[18];
        item20 = readOnlySpan[19];
        item21 = readOnlySpan[20];
        item22 = readOnlySpan[21];
        item23 = readOnlySpan[22];
        item24 = readOnlySpan[23];
        item25 = readOnlySpan[24];
        item26 = readOnlySpan[25];
        item27 = readOnlySpan[26];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21, out T item22, out T item23, out T item24, out T item25, out T item26, out T item27, out T item28) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
        item13 = readOnlySpan[12];
        item14 = readOnlySpan[13];
        item15 = readOnlySpan[14];
        item16 = readOnlySpan[15];
        item17 = readOnlySpan[16];
        item18 = readOnlySpan[17];
        item19 = readOnlySpan[18];
        item20 = readOnlySpan[19];
        item21 = readOnlySpan[20];
        item22 = readOnlySpan[21];
        item23 = readOnlySpan[22];
        item24 = readOnlySpan[23];
        item25 = readOnlySpan[24];
        item26 = readOnlySpan[25];
        item27 = readOnlySpan[26];
        item28 = readOnlySpan[27];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21, out T item22, out T item23, out T item24, out T item25, out T item26, out T item27, out T item28, out T item29) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
        item13 = readOnlySpan[12];
        item14 = readOnlySpan[13];
        item15 = readOnlySpan[14];
        item16 = readOnlySpan[15];
        item17 = readOnlySpan[16];
        item18 = readOnlySpan[17];
        item19 = readOnlySpan[18];
        item20 = readOnlySpan[19];
        item21 = readOnlySpan[20];
        item22 = readOnlySpan[21];
        item23 = readOnlySpan[22];
        item24 = readOnlySpan[23];
        item25 = readOnlySpan[24];
        item26 = readOnlySpan[25];
        item27 = readOnlySpan[26];
        item28 = readOnlySpan[27];
        item29 = readOnlySpan[28];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this ReadOnlySpan<T> readOnlySpan, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21, out T item22, out T item23, out T item24, out T item25, out T item26, out T item27, out T item28, out T item29, out T item30) {
        item1 = readOnlySpan[0];
        item2 = readOnlySpan[1];
        item3 = readOnlySpan[2];
        item4 = readOnlySpan[3];
        item5 = readOnlySpan[4];
        item6 = readOnlySpan[5];
        item7 = readOnlySpan[6];
        item8 = readOnlySpan[7];
        item9 = readOnlySpan[8];
        item10 = readOnlySpan[9];
        item11 = readOnlySpan[10];
        item12 = readOnlySpan[11];
        item13 = readOnlySpan[12];
        item14 = readOnlySpan[13];
        item15 = readOnlySpan[14];
        item16 = readOnlySpan[15];
        item17 = readOnlySpan[16];
        item18 = readOnlySpan[17];
        item19 = readOnlySpan[18];
        item20 = readOnlySpan[19];
        item21 = readOnlySpan[20];
        item22 = readOnlySpan[21];
        item23 = readOnlySpan[22];
        item24 = readOnlySpan[23];
        item25 = readOnlySpan[24];
        item26 = readOnlySpan[25];
        item27 = readOnlySpan[26];
        item28 = readOnlySpan[27];
        item29 = readOnlySpan[28];
        item30 = readOnlySpan[29];
    }

}
