// Do not edit this file directly!!!!!
namespace Bluehill.Deconstructors;

[EditorBrowsable(EditorBrowsableState.Never)]
public static class ListDeconstructors {
    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1) {
        item1 = list[0];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2) {
        item1 = list[0];
        item2 = list[1];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
        item13 = list[12];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
        item13 = list[12];
        item14 = list[13];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
        item13 = list[12];
        item14 = list[13];
        item15 = list[14];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
        item13 = list[12];
        item14 = list[13];
        item15 = list[14];
        item16 = list[15];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
        item13 = list[12];
        item14 = list[13];
        item15 = list[14];
        item16 = list[15];
        item17 = list[16];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
        item13 = list[12];
        item14 = list[13];
        item15 = list[14];
        item16 = list[15];
        item17 = list[16];
        item18 = list[17];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
        item13 = list[12];
        item14 = list[13];
        item15 = list[14];
        item16 = list[15];
        item17 = list[16];
        item18 = list[17];
        item19 = list[18];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
        item13 = list[12];
        item14 = list[13];
        item15 = list[14];
        item16 = list[15];
        item17 = list[16];
        item18 = list[17];
        item19 = list[18];
        item20 = list[19];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
        item13 = list[12];
        item14 = list[13];
        item15 = list[14];
        item16 = list[15];
        item17 = list[16];
        item18 = list[17];
        item19 = list[18];
        item20 = list[19];
        item21 = list[20];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21, out T item22) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
        item13 = list[12];
        item14 = list[13];
        item15 = list[14];
        item16 = list[15];
        item17 = list[16];
        item18 = list[17];
        item19 = list[18];
        item20 = list[19];
        item21 = list[20];
        item22 = list[21];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21, out T item22, out T item23) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
        item13 = list[12];
        item14 = list[13];
        item15 = list[14];
        item16 = list[15];
        item17 = list[16];
        item18 = list[17];
        item19 = list[18];
        item20 = list[19];
        item21 = list[20];
        item22 = list[21];
        item23 = list[22];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21, out T item22, out T item23, out T item24) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
        item13 = list[12];
        item14 = list[13];
        item15 = list[14];
        item16 = list[15];
        item17 = list[16];
        item18 = list[17];
        item19 = list[18];
        item20 = list[19];
        item21 = list[20];
        item22 = list[21];
        item23 = list[22];
        item24 = list[23];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21, out T item22, out T item23, out T item24, out T item25) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
        item13 = list[12];
        item14 = list[13];
        item15 = list[14];
        item16 = list[15];
        item17 = list[16];
        item18 = list[17];
        item19 = list[18];
        item20 = list[19];
        item21 = list[20];
        item22 = list[21];
        item23 = list[22];
        item24 = list[23];
        item25 = list[24];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21, out T item22, out T item23, out T item24, out T item25, out T item26) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
        item13 = list[12];
        item14 = list[13];
        item15 = list[14];
        item16 = list[15];
        item17 = list[16];
        item18 = list[17];
        item19 = list[18];
        item20 = list[19];
        item21 = list[20];
        item22 = list[21];
        item23 = list[22];
        item24 = list[23];
        item25 = list[24];
        item26 = list[25];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21, out T item22, out T item23, out T item24, out T item25, out T item26, out T item27) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
        item13 = list[12];
        item14 = list[13];
        item15 = list[14];
        item16 = list[15];
        item17 = list[16];
        item18 = list[17];
        item19 = list[18];
        item20 = list[19];
        item21 = list[20];
        item22 = list[21];
        item23 = list[22];
        item24 = list[23];
        item25 = list[24];
        item26 = list[25];
        item27 = list[26];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21, out T item22, out T item23, out T item24, out T item25, out T item26, out T item27, out T item28) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
        item13 = list[12];
        item14 = list[13];
        item15 = list[14];
        item16 = list[15];
        item17 = list[16];
        item18 = list[17];
        item19 = list[18];
        item20 = list[19];
        item21 = list[20];
        item22 = list[21];
        item23 = list[22];
        item24 = list[23];
        item25 = list[24];
        item26 = list[25];
        item27 = list[26];
        item28 = list[27];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21, out T item22, out T item23, out T item24, out T item25, out T item26, out T item27, out T item28, out T item29) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
        item13 = list[12];
        item14 = list[13];
        item15 = list[14];
        item16 = list[15];
        item17 = list[16];
        item18 = list[17];
        item19 = list[18];
        item20 = list[19];
        item21 = list[20];
        item22 = list[21];
        item23 = list[22];
        item24 = list[23];
        item25 = list[24];
        item26 = list[25];
        item27 = list[26];
        item28 = list[27];
        item29 = list[28];
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<T>(this IList<T> list, out T item1, out T item2, out T item3, out T item4, out T item5, out T item6, out T item7, out T item8, out T item9, out T item10, out T item11, out T item12, out T item13, out T item14, out T item15, out T item16, out T item17, out T item18, out T item19, out T item20, out T item21, out T item22, out T item23, out T item24, out T item25, out T item26, out T item27, out T item28, out T item29, out T item30) {
        item1 = list[0];
        item2 = list[1];
        item3 = list[2];
        item4 = list[3];
        item5 = list[4];
        item6 = list[5];
        item7 = list[6];
        item8 = list[7];
        item9 = list[8];
        item10 = list[9];
        item11 = list[10];
        item12 = list[11];
        item13 = list[12];
        item14 = list[13];
        item15 = list[14];
        item16 = list[15];
        item17 = list[16];
        item18 = list[17];
        item19 = list[18];
        item20 = list[19];
        item21 = list[20];
        item22 = list[21];
        item23 = list[22];
        item24 = list[23];
        item25 = list[24];
        item26 = list[25];
        item27 = list[26];
        item28 = list[27];
        item29 = list[28];
        item30 = list[29];
    }

}
